# NUMPY COPY

In [ ]:
# deepcopy:
# - np.copy > b = np.copy(a)
# - array.copy > b = a.copy()
# - np.array > b = np.array(a)

# shalowcopy:
# - a[:] > b = a[:]
# - a.view() > b = a.view()
# - b = a

In [ ]:
import numpy as np

# Original array
original = np.array([1,2,3])

# Using np.copy() - creates a deep copy

In [ ]:
copied_np_copy = np.copy(original)
copied_np_copy[0] = 99
print("Original after np.copy() modification:",original)
print("Copied with np.copy():", copied_np_copy)

Original after np.copy() modification: [1 2 3]
Copied with np.copy(): [99  2  3]


# Using array.copy() - creates a deep copy

In [ ]:
copied_array_copy = original.copy()
copied_array_copy[1] = 88
print("Original after array.copy() modification", original)
print("Copied with array.copy():", copied_array_copy)

Original after array.copy() modification [1 2 3]
Copied with array.copy(): [ 1 88  3]


# Using slicing[:]-creates a shallow copy

In [ ]:
copied_slicing = original[:]
copied_slicing[2] = 77
print("Original after slicing modification:", original)
print("Copied with slicing:", copied_slicing)

Original after slicing modification: [ 1  2 77]
Copied with slicing: [ 1  2 77]


In [ ]:
# Original array
original = np.array([1,2,3])

# Using np.array()-creates a deep copy

In [ ]:
copied_np_array = np.array(original)
copied_np_array[0] = 66
print("Original after np.array() modification:", original)
print("Copied with np.array():", copied_np_array)

Original after np.array() modification: [1 2 3]
Copied with np.array(): [66  2  3]


# Using np.view()-creates a shallow copy

In [ ]:
copied_view  = original.view()
copied_view[0] = 44
print("Original after np.view() modification:", original)
print("Copied with np.view():", copied_view)

Original after np.view() modification: [44  2  3]
Copied with np.view(): [44  2  3]


In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.transpose(arr)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

# Broadcasting in Numpy

In [ ]:
import numpy as np

# Ex1.Adding a scalar to an array

In [ ]:
a = np.array([1,2,3])
print("Original array:", a)
print("Scalar to add: 5")
b = a+ 5
print("Resulting array:", b)

Original array: [1 2 3]
Scalar to add: 5
Resulting array: [6 7 8]


# Ex2. Adding arrays of different shapes

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print("Array a:\n", a)
print("Array b:\n", b)
result = a + b
print("Result:\n", result)

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]]


# Ex3.Broadcasting with multidimensional

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
print("Array a:\n", a)
print("Array b:\n", b)
result = a + b
print("Result:\n", result)

Array a:
 [[1]
 [2]
 [3]]
Array b:
 [10 20 30]
Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


# Ex4:Multiplying arrays with broadcasting

In [ ]:
a = np.array([1,2,3])
b = np.array([[2],[4],[6]])
print("Array a:\n", a)
print("Array b:\n", b)
result = a * b
print("Result:\n",result)

Array a:
 [1 2 3]
Array b:
 [[2]
 [4]
 [6]]
Result:
 [[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]


# Ex5:Broadcasting error

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print("Array a:\n", a)
print("Array b:\n", b)
try:
    result = a + b
except ValueError as e:
    print("Error:",e)

Array a:
 [1 2 3]
Array b:
 [[1 2]
 [3 4]]
Error: operands could not be broadcast together with shapes (3,) (2,2) 


# Creating NumPy Arrays from Python Lists

## 1.Creating a 1D NumPy Array

In [ ]:
import numpy as np
list_1d = [1,2,3,4,5]
array_1d = np.array(list_1d)

print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


## 2.Creating a 2D NumPy Array

In [ ]:
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(list_2d)

print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3.Creating a 3D NumPy Array

In [ ]:
list_3d = [
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
]
array_3d = np.array(list_3d)
print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Checking the shape of the arrays

In [ ]:
print("Shape of 1D array:", array_1d.shape)
print("Shape of 2D array:", array_2d.shape)
print("Shape of 3D array:",array_3d.shape)

Shape of 1D array: (5,)
Shape of 2D array: (3, 3)
Shape of 3D array: (2, 2, 3)


# Creating NumPy Arrays from Python Tuples

## 1.Creating a 1D NumPy Array

In [ ]:
import numpy as np
tuple_1d = (1,2,3,4,5)
array_1d = np.array(tuple_1d)

print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


## 2.Creating a 2D NumPy Array

In [ ]:
tuple_2d = ((1,2,3),(4,5,6),(7,8,9))
array_2d = np.array(tuple_2d)

print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3.Creating a 3D NumPy Array

In [ ]:
tuple_3d = (
    ((1,2,3),(4,5,6)),
    ((7,8,9),(10,11,12))
)

array_3d = np.array(tuple_3d)
print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 4.Checking the shape of the array

In [ ]:
print("Shape of 1D array:",array_1d.shape)
print("Shape of 2D array:", array_2d.shape)
print("Shape of 3D array:", array_3d.shape)


Shape of 1D array: (5,)
Shape of 2D array: (3, 3)
Shape of 3D array: (2, 2, 3)


# Creating NumPy Arrays Using np.arange()

## 1.Creating a 1D Numpy Array

In [ ]:
array_1d = np.arange(1,11,2)

print("1D Array:")
print(array_1d)

1D Array:
[1 3 5 7 9]


## 2.Creating a 2D NumPy Array

In [ ]:
array_2d = np.arange(1,10).reshape(3,3)
print("2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3.Creating a 3D NumPy Array

In [ ]:
array_3d = np.arange(1, 13).reshape(2,2,3)
print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 4.Checking the Shape of the Arrays

In [ ]:
print("Shape of 1D array:",array_1d.shape)
print("Shape of 2D array:",array_2d.shape)
print("Shape of 3D array:", array_3d.shape)

Shape of 1D array: (5,)
Shape of 2D array: (3, 3)
Shape of 3D array: (2, 2, 3)


# Creating NumPy Arrays Using np.linspace()

## 1.Understanding the num Parameter

In [ ]:
import numpy as np
array_default = np.linspace(1,10)

array_custom = np.linspace(1,10,5)

print("Default num=50, First 5 values:", array_default[:5])
print("Custom num=5:",array_custom)

Default num=50, First 5 values: [1.         1.18367347 1.36734694 1.55102041 1.73469388]
Custom num=5: [ 1.    3.25  5.5   7.75 10.  ]


## 2,.Understanding the endpoint Parameter

In [ ]:
array_with_endpoint = np.linspace(1,110,5, endpoint=True)
array_without_endpoint = np.linspace(1,10,5, endpoint=False)

print("With endpoint=True:", array_with_endpoint)
print("Without endpoint=False:", array_without_endpoint)

With endpoint=True: [  1.    28.25  55.5   82.75 110.  ]
Without endpoint=False: [1.  2.8 4.6 6.4 8.2]


## 3.Understanding the retsetep Parameter

In [ ]:
array_with_step,step = np.linspace(1,10,5,retstep=True)
print("Array:",array_with_step)
print("Step size:",step)

Array: [ 1.    3.25  5.5   7.75 10.  ]
Step size: 2.25


## 4.Creating 1D,2D and 3D Array Using np.linspace()

### **1D** **Array**

In [ ]:
array_1d = np.linspace(1,10,5)
print("1D Array:",array_1d)

1D Array: [ 1.    3.25  5.5   7.75 10.  ]


## **2D Array**

In [ ]:
import numpy as np

array_2d = np.linspace(1, 9, 9).reshape(3, 3)
print("2D Array:\n", array_2d)


2D Array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## **3D Array**

In [ ]:
array_3d = np.linspace(1,12,12).reshape(2,2,3)
print("3D Array:\n", array_3d)

3D Array:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


# Creating NumPy Arrays Using ones,zeros, and empty

## 1. Creating Arrays Using np.ones()

In [ ]:
import numpy as np
# 1D array of ones
array_1d = np.ones(5)

# 2D array of ones
array_2d = np.ones((3,3))

# 2D array of ones
array_3d = np.ones((2,2,3))

print("1D Array of ones:\n", array_1d)
print("2D Array of ones:\n", array_2d)
print("3D Array of ones:\n", array_3d)

1D Array of ones:
 [1. 1. 1. 1. 1.]
2D Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3D Array of ones:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 2.Creating Arrays Using np.zero()

In [ ]:
# 1D array of zeros
array_1d = np.zeros(5)

# 2D array of zeros
array_2d = np.zeros((3,3))

# 3D array of zeros
array_3d = np.zeros((2,2,3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)

1D Array:
 [0. 0. 0. 0. 0.]
2D Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3D Array:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


## 3.Creating Arrays Using np.empty()

In [ ]:
# 1D empty array
array_1d = np.empty(5)

# 2D empty array
array_2d = np.empty((3,3))

# 3D empty array
array_3d = np.empty((2,2,3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)

1D Array:
 [0. 0. 0. 0. 0.]
2D Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3D Array:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
array_1 = np.empty(5)
array_1

array([0., 0., 0., 0., 0.])

In [ ]:
import numpy as np

# 1D empty array
array_1d = np.empty(5)

# 2D empty array
array_2d = np.empty((3, 3))

# 3D empty array
array_3d = np.empty((2, 2, 3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)


1D Array:
 [0. 0. 0. 0. 0.]
2D Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3D Array:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
import numpy as np

# 1D empty array
array_1d = np.empty(5)

# 2D empty array
array_2d = np.empty((3, 3))

# 3D empty array
array_3d = np.empty((2, 2, 3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)


1D Array:
 [0. 0. 0. 0. 0.]
2D Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3D Array:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
import numpy as np

# 1D empty array
array_1d = np.empty(5)
print("1D Array:\n", array_1d)

1D Array:
 [0. 0. 0. 0. 0.]


In [ ]:
# 2D empty array
array_2d = np.empty((3, 3))
print("2D Array:\n", array_2d)

2D Array:
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [ ]:
# 3D empty array
array_3d = np.empty((2, 2, 3))
print("3D Array:\n", array_3d)

3D Array:
 [[[4.9e-324 9.9e-324 1.5e-323]
  [2.0e-323 2.5e-323 3.0e-323]]

 [[3.5e-323 4.0e-323 4.4e-323]
  [4.9e-323 5.4e-323 5.9e-323]]]


## 4.Specifying dtype (Data Type)

In [ ]:
# Integer ones array
int_ones = np.ones((2,2),dtype=int)

# Float zeros array
float_zeros = np.zeros((2,2), dtype=float)

print("Integer Ones Array:\n", int_ones)
print("Float Zeros Array:\n", float_zeros)

Integer Ones Array:
 [[1 1]
 [1 1]]
Float Zeros Array:
 [[0. 0.]
 [0. 0.]]


# Craeting NumPy Arrays Using full

## 1.Creating 1D Array Using np.full()

In [ ]:
import numpy as np

array_1d = np.full(5,7)
print("1D Array:\n", array_1d)

1D Array:
 [7 7 7 7 7]


## 2.Creating 2D array Using np.full()

In [ ]:
array_2d = np.full((3,3),-3)
print("2D Array:\n", array_2d)

2D Array:
 [[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]


## 3.CReating 3D array using np.full()

In [ ]:
array_3d = np.full((2,2,3),9.99)
print("2D Array:\n", array_3d)

2D Array:
 [[[9.99 9.99 9.99]
  [9.99 9.99 9.99]]

 [[9.99 9.99 9.99]
  [9.99 9.99 9.99]]]


## 4.Specifying dtype While USing np.full()

In [ ]:
array_int = np.full((2,2),5,dtype=int)
array_float = np.full((2,2),2.5,dtype=float)

print("Integer Array:\n",array_int)
print("Float Array:\n", array_float)

Integer Array:
 [[5 5]
 [5 5]]
Float Array:
 [[2.5 2.5]
 [2.5 2.5]]


# Creating NumPy Arrays Using eye and identity

## 1.Creating an identity Matrix Using np.eye()

In [ ]:
import numpy as np
matrix_eye = np.eye(3)
print("3x3 Identity Matrix using np.eye():\n", matrix_eye)

3x3 Identity Matrix using np.eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2.Creating a Non-Square Matrix Using np.eye()

In [ ]:
matrix_eye_rectangular = np.eye(3,4)

print("3x3 Matrix using np.eye():\n",matrix_eye_rectangular)

3x3 Matrix using np.eye():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## 3.Using the k Parameter in np.eye()

In [ ]:
matrix_eye_upper = np.eye(4,k=1)
matrix_eye_lower = np.eye(4,k=-1)

print("Upper Daigonal (k=1):\n", matrix_eye_upper)
print("Lower Daigonal (k=-1):\n", matrix_eye_lower)

Upper Daigonal (k=1):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
Lower Daigonal (k=-1):
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## 4.Creating an identity matrix using np.identity()

In [ ]:
matrix_identity = np.identity(4)
print("4x4 Identity Matrix using np.identity ():\n", matrix_identity)

4x4 Identity Matrix using np.identity ():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Creating NumPy Arrays Using random,random.random,rand,randan and randint

## 1.Using np.random.random()

In [ ]:
import numpy as np
array_random = np.random.random(5)
print("1D Array using np.random.random():\n", array_random)

1D Array using np.random.random():
 [0.35918151 0.87913979 0.50777627 0.28039239 0.0569772 ]


## 2.Using np.random.rand()

In [ ]:
array_rand = np.random.rand(2,3)
print("2D Array using np.random.rand():\n", array_rand)

2D Array using np.random.rand():
 [[0.56486206 0.29584744 0.31248319]
 [0.29081893 0.09684258 0.25831174]]


## 3.Using np.random.randn()

In [ ]:
array_randn = np.random.randn(3,3)
print("3x3 Array using np.random.randn():\n", array_randn)

3x3 Array using np.random.randn():
 [[ 0.5965023   0.53025242 -1.64726499]
 [-0.60999535 -0.03898752 -0.21453141]
 [ 2.15058331 -0.48866196  1.27374802]]


## 4.Using np.random.randint()

In [ ]:
array_randint = np.random.randint(10,50,(4,4))
print("4x4 Array using np.random.randint():\n",array_randint)

4x4 Array using np.random.randint():
 [[44 14 16 39]
 [17 39 39 20]
 [14 41 12 28]
 [15 37 25 20]]


# Creating NumPy Array Using astype to Specifi data type

## 2.Converting an Array to int

In [ ]:
import numpy as np

# Creating a NumPy array of floats
arr_float = np.array([1.5, 2.8, 3.9, 4.2])

# Converting to integers
arr_int = arr_float.astype(int)

print("Original Float Array:\n", arr_float)
print("Converted Integer Array:\n", arr_int)

Original Float Array:
 [1.5 2.8 3.9 4.2]
Converted Integer Array:
 [1 2 3 4]


## 3.Converting an Array to float

In [ ]:
# Creating an array of integers
arr_int = np.array([1, 2, 3, 4])

# Converting to float
arr_float = arr_int.astype(float)

print("Integer Array:\n", arr_int)
print("Converted Float Array:\n", arr_float)

Integer Array:
 [1 2 3 4]
Converted Float Array:
 [1. 2. 3. 4.]


## 4.Converting an Array to bool

In [ ]:
# Creating an array with integers
arr = np.array([0, 1, 2, 0, -3, 4])

# Converting to boolean
arr_bool = arr.astype(bool)

print("Original Array:\n", arr)
print("Converted Boolean Array:\n", arr_bool)

Original Array:
 [ 0  1  2  0 -3  4]
Converted Boolean Array:
 [False  True  True False  True  True]


## 5.Converting an Array to complex

In [ ]:
# Creating an integer array
arr = np.array([1, 2, 3, 4])

# Converting to complex
arr_complex = arr.astype(complex)

print("Integer Array:\n", arr)
print("Converted Complex Array:\n", arr_complex)

Integer Array:
 [1 2 3 4]
Converted Complex Array:
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## 6.Using astype() with String conversion

In [ ]:
# Creating a NumPy array of integers
arr = np.array([10, 20, 30])

# Converting to string
arr_str = arr.astype(str)

print("Integer Array:\n", arr)
print("Converted String Array:\n", arr_str)

Integer Array:
 [10 20 30]
Converted String Array:
 ['10' '20' '30']


# Creating a New Numpy Array Using reshape

## 1.Reshaping a 1D Array to a 2D Array

In [ ]:
import numpy as np

# Creating a 1D array of 6 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2D array (2 rows, 3 columns)
arr_2d = arr_1d.reshape(2, 3)

print("Original 1D Array:\n", arr_1d)
print("Reshaped 2D Array:\n", arr_2d)

Original 1D Array:
 [1 2 3 4 5 6]
Reshaped 2D Array:
 [[1 2 3]
 [4 5 6]]


## 3.Reshaping a 1D Array to a 3D array

In [ ]:
# Creating a 1D array of 12 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping into a 3D array (2 blocks, 2 rows, 3 columns)
arr_3d = arr_1d.reshape(2, 2, 3)

print("Reshaped 3D Array:\n", arr_3d)

Reshaped 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 4.Using -1 to Let Numpy calculacte Shape Automatically

In [ ]:
arr_auto = arr_1d.reshape(-1,3)
print("Reshaped Using -1:\n",arr_auto)

Reshaped Using -1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 5.Reshaping a 2D Array to 1D (flattening)

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])

arr_flattened = arr_2d.reshape(-1)

print("Flattened 1D Array:\n", arr_flattened)

Flattened 1D Array:
 [1 2 3 4 5 6]


# Using tile to Repeat Arrays

## 1.Understanding tile()

## 2.Repeting a 1D Array

In [ ]:
arr_1d = np.array([1,2,3])
tiled_1d = np.tile(arr_1d,3)
print("Original 1D Array:", arr_1d)
print("Tiled 1D Array:", tiled_1d)

Original 1D Array: [1 2 3]
Tiled 1D Array: [1 2 3 1 2 3 1 2 3]


## 3.Repeting a 2D Array Along Both Axes

In [ ]:
arr_2d = np.array([[1,2],[3,4]])
tiled_2d = np.tile(arr_2d,(2,3))
print("Original 2D Array:\n", arr_2d)
print("Tiled 2D Array:\n", tiled_2d)

Original 2D Array:
 [[1 2]
 [3 4]]
Tiled 2D Array:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 4.Repeating a 3D Array

In [ ]:
arr_3d = np.array([[[1,2]],[[3,4]]])
tiled_3d = np.tile(arr_3d,(2,2,2))
print("Original 3D ARray:\n", arr_3d)
print("Tiled 3D Array:\n",tiled_3d)

Original 3D ARray:
 [[[1 2]]

 [[3 4]]]
Tiled 3D Array:
 [[[1 2 1 2]
  [1 2 1 2]]

 [[3 4 3 4]
  [3 4 3 4]]

 [[1 2 1 2]
  [1 2 1 2]]

 [[3 4 3 4]
  [3 4 3 4]]]


## 5.Difference Between tile() and repeat()

In [ ]:
arr = np.array([1,2,3])

print(np.tile(arr,2))

print(np.repeat(arr,2))

[1 2 3 1 2 3]
[1 1 2 2 3 3]


# Using fromfunction to Create Arrays

## 1.Cre4ating a Simple 2D Array

In [ ]:
import numpy as np
def func(x,y):
    return x + y

arr = np.fromfunction(func,(3,3),dtype=int)

print("Generated 2D Array:\n",arr)

Generated 2D Array:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


## 2.Creating a multiplication table

In [ ]:
def multiply(x,y):
    return(x + y)*(y + 1)

multiplication_table = np.fromfunction(multiply, (5,5),dtype=int)

print("5x5 Multiplication Table:\n", multiplication_table)

5x5 Multiplication Table:
 [[ 0  2  6 12 20]
 [ 1  4  9 16 25]
 [ 2  6 12 20 30]
 [ 3  8 15 24 35]
 [ 4 10 18 28 40]]


## 4.Creating a 3D Array

In [ ]:
def three_d(x,y,z):
     return x + y * z

arr_3d = np.fromfunction(three_d,(3,3,3),dtype=int)
print("Generated 3D Array:\n",arr_3d)

Generated 3D Array:
 [[[0 0 0]
  [0 1 2]
  [0 2 4]]

 [[1 1 1]
  [1 2 3]
  [1 3 5]]

 [[2 2 2]
  [2 3 4]
  [2 4 6]]]


## 5.Using fromfunction() with a Bolean Function

In [ ]:
def is_even(x,y):
    return(x+y)% 2 == 0

bool_mask = np.fromfunction(is_even,(5,5),dtype=int)
print("Boolean Mask Array:\n",bool_mask)

Boolean Mask Array:
 [[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


In [ ]:
print("Boolean Mask Array:\n",bool_mask)

Boolean Mask Array:
 [[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


In [ ]:
import numpy as np

def is_even(x, y):
    return (x + y) % 2 == 0

# Creating a 5x5 boolean mask and converting to integers
bool_mask = np.fromfunction(is_even, (5, 5), dtype=int).astype(int)

print("Boolean Mask Array:\n", bool_mask)

Boolean Mask Array:
 [[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


# Using fromiter to Create Arrays

## Creating an Array from a List

In [ ]:
import numpy as np
my_list = [1,2,3,4,5]
arr = np.fromiter(my_list, dtype=int)
print("NumPy Array:\n", arr)

NumPy Array:
 [1 2 3 4 5]


## Creating an Array from a Tuple

In [ ]:
my_tuple = (10,20,30,40)
arr = np.fromiter(my_tuple, dtype=int)
print("NumPy Array from Tuple:\n", arr)

NumPy Array from Tuple:
 [10 20 30 40]


## Creating an Array from a Generator

In [ ]:
def squares(n):
    for i in range(n):
        yield i ** 2

arr = np.fromiter(squares(5), dtype=int)
print("NumPy Array from Generator:\n", arr)

NumPy Array from Generator:
 [ 0  1  4  9 16]


## Using count Parameter


In [ ]:
iterable = iter(range(10))

arr = np.fromiter(iterable, dtype=int, count=5)

print("NumPy Array with Limited Elements:\n", arr)

NumPy Array with Limited Elements:
 [0 1 2 3 4]


## CReating a Diagonal Matrix from 1D Array

In [ ]:
arr = np.array([1,2,3,4])

diag_matrix = np.diag(arr)
print("Diagonal Matrix:\n", diag_matrix)

Diagonal Matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Creating a Digonal Matrix an offset

In [ ]:
diag_matrix_upper = np.diag(arr, k=1)

print("Diagonal Matrix with k=1:\n", diag_matrix_upper)

Diagonal Matrix with k=1:
 [[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [ ]:
diag_matrix_lower = np.diag(arr,k=-1)
print("Diagonal Matrix with k=-1:\n", diag_matrix_lower)

Diagonal Matrix with k=-1:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Extracting the Diagonal from a 2D Matrix

In [ ]:
matrix = np.array([[5,1,3],
                   [2,8,4],
                   [7,6,9]])
main_diag = np.diag(matrix)
print("Extracted Main Diagonal:\n", main_diag)

Extracted Main Diagonal:
 [5 8 9]


In [ ]:
upper_diag = np.diag(matrix, k=1)
print("Extracted Upper Diagonal:\n", upper_diag)

Extracted Upper Diagonal:
 [1 4]


In [ ]:
lower_diag = np.diag(matrix, k=-1)
print("Extracted Lower Diagonal:\n", lower_diag)

Extracted Lower Diagonal:
 [2 6]


# Array indexing

In [ ]:
import numpy as np
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[9]

np.int64(9)

In [ ]:
a[-9]

np.int64(2)

In [ ]:
a[4]

np.int64(4)

## Slicing 1D array

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[1:4]

array([1, 2, 3])

In [ ]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_a = a[0:5]

In [ ]:
slice_a

array([0, 1, 2, 3, 4])

In [ ]:
slice_a[:] = 100
slice_a

array([100, 100, 100, 100, 100])

In [ ]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## STEP

In [ ]:
a = np.arange(0,11)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
a[1:6:1]

array([1, 2, 3, 4, 5])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
a_copy = a.copy()
a_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = a[:]

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array(matrices)

In [ ]:
mat = np.array(([5,10,20],[20,25,30],[35,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [ ]:
mat.shape

(3, 3)

In [ ]:
mat[1]

array([20, 25, 30])

In [ ]:
mat[2]

array([35, 40, 10])

In [ ]:
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [ ]:
mat[1][1]

np.int64(25)

In [ ]:
mat[1,2]

np.int64(30)

In [ ]:
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [ ]:
mat[:,:]

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [ ]:
mat[:,[0,1]]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [ ]:
arr2 = np.arange(25).reshape(5,5)

In [ ]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[[0,2,4],:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[::2,:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [ ]:
arr2[1:3,[0,1,3,4]]

array([[ 5,  6,  8,  9],
       [10, 11, 13, 14]])

In [ ]:
arr2[2:4,3:]

array([[13, 14],
       [18, 19]])

In [ ]:
arr2[1::2,::4]

array([[ 5,  9],
       [15, 19]])

In [ ]:
arr2[1:3,[0,4]]

array([[ 5,  9],
       [10, 14]])

In [ ]:
arr2[::4,::4]

array([[ 0,  4],
       [20, 24]])

In [ ]:
arr2[2:,[3,4]]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [ ]:
arr2[[1,3],1:]

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19]])

In [ ]:
arr2[[3,4],3:]

array([[18, 19],
       [23, 24]])

In [ ]:
mat[0]

array([ 5, 10, 20])

In [ ]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [ ]:
mat[2]

array([35, 40, 10])

In [ ]:
mat[2,:]

array([35, 40, 10])

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a[1,5]

np.int64(13)

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
b[0,1,1]

np.int64(4)

In [ ]:
import numpy as np

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
# Generate matrix:

###    1  2  3  4  5
###    6  7  8  9 10
###   11 12 13 14 15
###   16 17 18 19 20
###   21 22 23 24 25
###   26 27 28 29 30

# Acces
        11 12
        16 17

# Acces
         2
           8
            14
              20

# Acces
                4  5



               24 25
               29 30

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 25)

## Boolean array indexing

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[[True,True,True,False,False,False,False,False,False,False]]

array([1, 2, 3])

In [ ]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_a = a>4

In [ ]:
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
a[a>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)

bool_idx = (a>2)

print(bool_idx)

print(a[bool_idx])


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


# Advanced Indexing and Slicing

### 1D

In [ ]:
import numpy as np
a1 = np.arange(20)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a1[1:4]

array([1, 2, 3])

In [ ]:
a1[1:10:2]

array([1, 3, 5, 7, 9])

In [ ]:
a1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1[[0,19]]

array([ 0, 19])

In [ ]:
a1[[0,-1]]

array([ 0, 19])

In [ ]:
a1[::19]

array([ 0, 19])

In [ ]:
a1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a1[[1,6,19]]

array([ 1,  6, 19])

In [ ]:
a2 = np.arange(12).reshape(4,3)

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2[::2,:]

array([[0, 1, 2],
       [6, 7, 8]])

In [ ]:
a2[:,[0,2]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [ ]:
a2[:,::2]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2[:,[0]]

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
a2[:,::3]

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
a2[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [ ]:
a2[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [ ]:
a2[::3]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [ ]:
a2[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
a2[[1,2],0:1]

array([[3],
       [6]])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2[::2,::2]

array([[0, 2],
       [6, 8]])

In [ ]:
a2[1::2,::2]

array([[ 3,  5],
       [ 9, 11]])

### 2D

In [ ]:
b2 = np.arange(25).reshape(5,5)

In [ ]:
b2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
b2[:,[0,1,4]]

array([[ 0,  1,  4],
       [ 5,  6,  9],
       [10, 11, 14],
       [15, 16, 19],
       [20, 21, 24]])

In [ ]:
b2[2:4,2:4]

array([[12, 13],
       [17, 18]])

In [ ]:
b2[2:4,1::3]

array([[11, 14],
       [16, 19]])

In [ ]:
b2[::4,::4]

array([[ 0,  4],
       [20, 24]])

In [ ]:
b2[1:3,[0,4]]

array([[ 5,  9],
       [10, 14]])

In [ ]:
sq = np.arange(9).reshape(3,3)
sq

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10 most commonly used NumPy mathematical operations

In [ ]:
import numpy as np

# ex1: Array creation
print("1. Array Creation:")
a = np.array([1,2,3,4,5])
print("Array:",a)

1. Array Creation:
Array: [1 2 3 4 5]


In [ ]:
# Ex: Element-wise arithmetic operations
print("\n2. Element-wise Arithematic Operations:")
b = np.array([6,7,8,9,10])
print("array1:", a)
print("array b:", b)

# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", a - b)

# Multiplication
print("Multiplication:", a * b)

# Division
print("Division:", a / b)


2. Element-wise Arithematic Operations:
array1: [1 2 3 4 5]
array b: [ 6  7  8  9 10]
Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
# Ex3: Array broadcasting
print("\n3. Array Broadcasting:")
c = np.array([[1,2,3],[4,5,6]])
print("Original Array:")
print(c)

# Add sscalar to array
print("Add Scalar to Array:")

# Multiply array by scalar
print("Multiply Array by Scalar:")
print(c * 2)


3. Array Broadcasting:
Original Array:
[[1 2 3]
 [4 5 6]]
Add Scalar to Array:
Multiply Array by Scalar:
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Ex4: Array aggregation functions
print("\n4. Array Aggregation Function:")
d = np.array([1,2,3,4,5])
print("Array:",d)

# Sum
print("Sum:", np.sum(d))

# Mean
print("Mean:",np.mean(d))

# Maximum
print("Maximum:", np.max(d))

# Minimum
print("Minimum:", np.min(d))


4. Array Aggregation Function:
Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Maximum: 5
Minimum: 1


In [ ]:
# Ex5: Array manipulation functions
print("\n5. Array Manipulation Function:")
e = np.array([[1,2],[3,4],[5,6]])
print("Original Array:")
print(e)


5. Array Manipulation Function:
Original Array:
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Transpose
print("Transpose:")
print(np.transpose(e))

# Reshape
print("Reshape:")
print(np.reshape(e,(2,3)))

# Flatten
print("Flatten:")
print(e.flatten())


Transpose:
[[1 3 5]
 [2 4 6]]
Reshape:
[[1 2 3]
 [4 5 6]]
Flatten:
[1 2 3 4 5 6]


In [ ]:
ar = np.arange(1,13).reshape(2,3,2)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Reshape
print("Reshape:")
print(np.reshape(ar,(2,3,2)))

Reshape:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Ex6: Array sorting
print("\n6. Array Sorting:")
f = np.array([5,2,9,1,7])
print("Origial Array:",f)

# Sort array
print("Sorted Array:", np.sort(f))


6. Array Sorting:
Origial Array: [5 2 9 1 7]
Sorted Array: [1 2 5 7 9]


In [ ]:
# Ex7: Linear algebra operations
print("\n7. Linear Algebra Operations:")
g = np.array([[1,2],[3,4]])
h = np.array([[5,6],[7,8]])

# Matrix multipication
print("Matrix Multiplication:")
print(np.dot(g, h))


7. Linear Algebra Operations:
Matrix Multiplication:
[[19 22]
 [43 50]]


In [ ]:
# Ex8: Random number generation
print("\n8.Random Number Generation:")

# Generate random integers
print("Random Integers:",np.random.randint(1,10, size=5))

# Generate random floats
print("Random Floats:", np.random.rand(5))


8.Random Number Generation:
Random Integers: [4 9 5 8 9]
Random Floats: [0.95111581 0.62822763 0.76630494 0.99323712 0.85670053]


In [ ]:
# Ex9: Trigonometric functions
print("\n9. Trigonometric Functions:")
i = np.array([0, np.pi/2, np.pi])
print("Array:",i)

# Sine
print("Sine:", np.sin(i))

# Cosine
print("Cosine:", np.cos(i))

# Tangent
print("Tangent:",np.tan(i))



9. Trigonometric Functions:
Array: [0.         1.57079633 3.14159265]
Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
# Ex 10: Exponential and logarithmic functions
print("\n10. Exponential and Logarithmic Functios:")
j = np.array([1,2,3])
print("Array:", j)

# Exponential
print("Exponential:", np.exp(j))

# Natural logarithm
print("Natural Logarithm:", np.log(j))




10. Exponential and Logarithmic Functios:
Array: [1 2 3]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural Logarithm: [0.         0.69314718 1.09861229]


# 1.Setup

In [ ]:
import numpy as np
import time

# 2.EX Problems:

## 2.1 Element-wise Operations on Arrays

In [ ]:
# Standard Python
size = 1000000
list1 = range(size)
list2 = range(size)

start_time = time.time()
result = [(x + y) for x, y in zip(list1, list2)]
end_time = time.time()
print("Standard Python:", end_time - start_time, "seconds")

# NumPy
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result = array1 + array2
end_time = time.time()
print("NumPy:", end_time - start_time, "seconds")

Standard Python: 0.1521449089050293 seconds
NumPy: 0.06187605857849121 seconds


## 2.2 Vectorized Operations vs. Loops

In [ ]:
# Standard Python
size = 1000000
list1 = range(size)

start_time = time.time()
result = [x * 2 for x in list1]
end_time = time.time()
print("Standard Python:", end_time - start_time, "seconds")

# NumPy
array1 = np.arange(size)

start_time = time.time()
result = array1 * 2
end_time = time.time()
print("NumPy:", end_time - start_time, "seconds")

Standard Python: 0.1456737518310547 seconds
NumPy: 0.030587434768676758 seconds


## 2.3 Matrix Multiplication

In [1]:
import numpy as np
import time

In [2]:
# Standard Python
size = 1000
matrix1 = [[1]*size for _ in range(size)]
matrix2 = [[1]* size for _ in range(size)]
result = [[0]* size for _ in range(size)]

start_time = time.time()
for i in range(size):
    for j in range(size):
        result[i][j] = sum(matrix1[i][k] * matrix2[k][j] for k in range(size) )
end_time = time.time()
print("Standard Python:", end_time - start_time, "seconds")

# NumPy
matrix1 = np.ones((size, size))
matrix2 = np.ones((size,size))

start_time = time.time()
result = np.dot(matrix1, matrix2)
end_time = time.time()
print("NumPy:", end_time - start_time,"seconds")

Standard Python: 131.1645588874817 seconds
NumPy: 0.05697798728942871 seconds


## 2.4 Statistical Operations

In [3]:
import numpy as np
import time

In [4]:
# Standard Python
size = 1000000
data = range(size)

start_time = time.time()
mean = sum(data) / size
end_time = time.time()
print("Standard Python:", end_time - start_time, "seconds")

# NumPy
data = np.arange(size)

start_time = time.time()
mean = np.mean(data)
end_time = time.time()
print("NumPuy:", end_time - start_time, "seconds")


Standard Python: 0.0521085262298584 seconds
NumPuy: 0.004530429840087891 seconds


## 2.5 Memort Usage Comparison

In [6]:
# Standard Python
import sys

# Create a list of integers
size = 1000000
list1 = [i for i in range(size)]

# Calculate memory usage of the list
list1_memory = sys.getsizeof(list1)
print("Standard Python List Memory:", list1_memory, "bytes")
print(type(list1_memory))
# NumPy
import numpy as np

# Create a NumPy array of integers
array1 = np.arange(size, dtype=np.int8)

# Calculate memory usage of the NumPy array
array1_memory = array1.nbytes
print("NumPy Array Memory:", array1_memory, "bytes")

Standard Python List Memory: 8448728 bytes
<class 'int'>
NumPy Array Memory: 1000000 bytes
